CREATE TABLE tbl_extended_color_light (
    unique_id
    name
    model_id
    manufacturer_name
    product_name
    software_version
    software_config_id
    product_id
    resource
    state_on
    state_bri
    state_hue
    state_sat
    state_effect
    state_xy_x
    state_xy_y
    state_ct
    state_alert
    state_color_mode
    state_mode
    state_reachable
)